[package]
name = "main-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
some_other_crate = "0.1.0"
another_nice_crate = "1.7"